
name: iOS Hello World

on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'APP Environment'
          type: environment
          required: true

jobs:
  build:
    name: Build and Test
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: |
        sudo xcode-select -switch /Applications/Xcode.app
        xcodebuild -downloadPlatform iOS --platform iOS --version 18.2
      
    - name: Build
      run: |
        echo "Hello from iOS GitHub Actions!"
        xcodebuild -version
        xcodebuild -showsdks