
name: iOS Hello World

on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'APP Environment'
          type: environment
          required: true

jobs:
  build:
    name: Build and Test
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v3
    - name: Choose Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
          xcode-version: '16.2.0'
    
    - name: Select Xcode
      run: |
        xcodebuild -version
        sudo xcode-select -switch /Applications/Xcode.app
        xcodebuild -downloadPlatform iOS -buildVersion 18.2
      
    - name: Build
      run: |
        echo "Hello from iOS GitHub Actions!"
        xcodebuild -version
        xcodebuild -showsdks