
name: iOS Hello World

on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'APP Environment'
          type: environment
          required: true

jobs:
  build:
    name: Build and Test
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v3
    - name: Choose Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
          xcode-version: '16.1.0'
    
    - name: Select Xcode
      run: |
        xcodebuild -version
        xcodebuild -showsdks
        # sudo xcode-select -switch /Applications/Xcode.app
        # sudo xcodebuild -downloadPlatform iOS
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        rm -rf ~/Library/Developer/Xcode/DerivedData
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -license accept
      
    - name: Build
      run: |
        echo "Hello from iOS GitHub Actions!"
        xcodebuild -version
        xcodebuild -showsdks